<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Accounts</title>
</head>
<body>
<h1>Account</h1>
<div>
    <h2>Name: ${account.firstName}</h2>
    <br>
    <h2>LastName: ${account.lastName}</h2>
    <br>
    <h2>Email: ${account.email}</h2>
</div>
</body>
</html>